---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8087'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.38.3
    ports:
    - 8087:8087
    - 50051:50051
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8087/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      ENABLE_MODULES: 'text2vec-huggingface'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /home/weaviate:/var/lib/weaviate
  
  text_embeddings_inference:
    image: ghcr.io/huggingface/text-embeddings-inference:1.9
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8090:80"
    volumes:
      - /home/huggingface-cache:/data
    environment:
      - MODEL_ID=BAAI/bge-m3
      - HUGGINGFACE_HUB_CACHE=/data/hub
      - MAX_CLIENT_BATCH_SIZE=200
    restart: always

  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['GPU-3cce1cf1-71b5-6d8e-2fd3-1f54d1b89d24'] # GPU_1
                #['GPU-c33c3b83-08c1-4e49-96f7-9ab1c6be7d23'] # GPU_0
              capabilities: [compute, utility]
    volumes:
      - /home/huggingface-cache/:/root/.cache/huggingface
      - ./vllm_config_qwen3.yaml:/app/config/vllm_config.yaml
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - "9513:9513"
    ipc: host
    command: --config /app/config/vllm_config.yaml